# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionactivity',
            name='last_activity',
            field=models.DateTimeField(null=True),
        ),
    ]
