# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_log', '0002_sessionactivity_time_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionactivity',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='sessionactivity',
            name='user_agent',
            field=models.TextField(null=True),
        ),
    ]
